;;; djot-modern-test.el --- Tests for Djot presentation -*- lexical-binding: t; -*-

(require 'ert)
(require 'djot-modern)

;; Fail, rather than skip, if the test environment lacks the grammar.
(unless (treesit-ready-p 'djot t)
  (error "Set DJOT_GRAMMAR_DIR to a directory containing libtree-sitter-djot"))

(defmacro djot-modern-test--buffer (text &rest body)
  "Run BODY in a visible-name text buffer containing TEXT."
  (declare (indent 1) (debug t))
  `(with-temp-buffer
     (rename-buffer (generate-new-buffer-name "djot-modern-test"))
     (text-mode)
     (insert ,text)
     (set-buffer-modified-p nil)
     (let ((noninteractive nil))
       (unwind-protect (progn ,@body)
         (when djot-modern-mode (djot-modern-mode -1))))))

(defun djot-modern-test--at (text &optional property)
  "Return PROPERTY at the start of TEXT, defaulting to face."
  (save-excursion
    (goto-char (point-min))
    (search-forward text)
    (get-text-property (- (point) (length text)) (or property 'face))))

(defun djot-modern-test--fontify ()
  "Ensure all accessible text has been fontified."
  (font-lock-ensure (point-min) (point-max)))

(ert-deftest djot-modern-test-features ()
  (djot-modern-test--buffer
      "# Title\n\n## Section\n\n- item\n- [ ] pending\n- [x] done\n\n> quote\n\n***\n\n*bold* _italic_ {=mark=} {+new+} {-old-} H~2~ x^2^\n\n[site](https://example.org) `literal`{.code}\n\n```elisp\n(+ 1 2)\n```\n\n| Name | Value |\n| ---- | ----- |\n| a | b |\n"
    (djot-modern-mode 1)
    (should font-lock-mode)
    (djot-modern-test--fontify)
    (dolist (pair '(("Title" . djot-modern-heading-1)
                    ("Section" . djot-modern-heading-2)
                    ("bold" . djot-modern-strong)
                    ("italic" . djot-modern-emphasis)
                    ("mark" . djot-modern-highlight)
                    ("new" . djot-modern-insert)
                    ("old-}" . djot-modern-delete)
                    ("2~" . djot-modern-script)
                    ("2^" . djot-modern-script)
                    ("site" . djot-modern-link)
                    ("literal" . djot-modern-code)
                    (".code" . djot-modern-label)
                    ("elisp" . djot-modern-label)
                    ("(+ 1" . djot-modern-code)
                    ("Name" . djot-modern-table)))
      (should (memq (cdr pair) (djot-modern-test--at (car pair)))))
    (dolist (pair '(("# " . "◉ ") ("- item" . "• ")
                    ("[ ]" . "☐") ("[x]" . "☑")
                    ("> " . "│ ") ("***" . "────────") ("| Name" . "│")))
      (should (equal (substring-no-properties
                      (djot-modern-test--at (car pair) 'display)) (cdr pair))))
    (should-not (djot-modern-test--at "*bold" 'display))
    (should-not (text-property-not-all (point-min) (point-max) 'invisible nil))))

(ert-deftest djot-modern-test-opaque-and-escaped ()
  (djot-modern-test--buffer
      "\\*not strong\\* and \\_not emphasis\\_\n\n`*literal* | # no`\n\n```\n# not heading\n\n- not bullet\n*not strong*\n```\n\n```=html\n# raw heading\n*raw strong*\n```\n\n| a\\|b | `x|y` |\n| ---- | ---- |\n"
    (djot-modern-mode 1)
    (djot-modern-test--fontify)
    (dolist (text '("not strong" "not emphasis" "literal" "not heading"
                    "not bullet" "raw heading" "raw strong"))
      (should-not (memq 'djot-modern-strong (djot-modern-test--at text)))
      (should-not (djot-modern-test--at text 'display)))
    (should-not (djot-modern-test--at "|b" 'display))
    (should-not (djot-modern-test--at "|y" 'display))))

(ert-deftest djot-modern-test-block-precedence-and-malformed ()
  (djot-modern-test--buffer
      "paragraph\n# not a heading\n- not a list\n\n*unclosed\n\n_This is *regular_ not strong*\n"
    (djot-modern-mode 1)
    (djot-modern-test--fontify)
    (should-not (djot-modern-test--at "# not" 'display))
    ;; Some grammar releases accept a list here contrary to the Djot spec.
    ;; Assert node-to-display consistency without requiring that bug to persist.
    (should (eq (not (null (djot-modern-test--at "- not" 'display)))
                (not (null (treesit-query-capture
                            djot-modern--parser '((list_marker_dash) @marker))))))
    (should-not (djot-modern-test--at "unclosed"))
    (should (memq 'djot-modern-emphasis (djot-modern-test--at "regular")))
    (should-not (memq 'djot-modern-strong (djot-modern-test--at "regular")))))

(ert-deftest djot-modern-test-lifecycle-read-only-and-undo ()
  (djot-modern-test--buffer "# Title\n\n- item\n"
    (buffer-enable-undo)
    (let ((text (buffer-string)) (undo buffer-undo-list)
          (buffer-read-only t))
      (dotimes (_ 3)
        (djot-modern-mode 1)
        (djot-modern-test--fontify)
        (djot-modern-mode 1)
        (should (= 1 (length (treesit-parser-list))))
        (djot-modern-mode -1)
        (should-not font-lock-mode)
        (should-not (treesit-parser-list))
        (should (equal text (buffer-substring-no-properties (point-min) (point-max))))
        (dolist (prop '(face display djot-modern--display invisible))
          (should-not (text-property-not-all (point-min) (point-max) prop nil)))
        (should (equal undo buffer-undo-list))
        (should-not (buffer-modified-p))))))

(defun djot-modern-test--undecorated (text)
  "Assert TEXT has no Djot presentation properties."
  (dotimes (pos (length text))
    (should-not (get-text-property pos 'djot-modern--display text))
    (let ((face (get-text-property pos 'face text)))
      (dolist (ours djot-modern--faces)
        (should-not (if (listp face) (memq ours face) (eq ours face)))))))

(ert-deftest djot-modern-test-delete-disable-undo ()
  (djot-modern-test--buffer "# Title\n\n- item\n"
    (buffer-enable-undo)
    (goto-char (point-max))
    (insert "earlier edit\n")
    (undo-boundary)
    (djot-modern-mode 1)
    (djot-modern-test--fontify)
    (with-silent-modifications
      (font-lock-prepend-text-property 1 3 'face 'warning)
      (put-text-property 1 3 'help-echo "keep"))
    (delete-region 1 3)
    (undo-boundary)
    (let ((history buffer-undo-list))
      (djot-modern-mode -1)
      (should (eq history buffer-undo-list)))
    (undo-only 1)
    (should (equal (buffer-substring-no-properties (point-min) (point-max))
                   "# Title\n\n- item\nearlier edit\n"))
    (let ((last-command 'undo)) (undo-only 1))
    (should (equal (buffer-substring-no-properties (point-min) (point-max))
                   "# Title\n\n- item\n"))
    (djot-modern-test--undecorated (buffer-string))
    (should-not (get-text-property 1 'display))
    (should (memq 'warning (get-text-property 1 'face)))
    (should (equal "keep" (get-text-property 1 'help-echo)))))

(ert-deftest djot-modern-test-active-delete-and-undo ()
  (djot-modern-test--buffer "# Title\n\n- item\n"
    (buffer-enable-undo)
    (djot-modern-mode 1)
    (djot-modern-test--fontify)
    (delete-region 1 3)
    (undo-boundary)
    (djot-modern-test--fontify)
    (should-not (memq 'djot-modern-heading-1 (djot-modern-test--at "Title")))
    (undo-only 1)
    (djot-modern-test--fontify)
    (should (djot-modern-test--at "# " 'display))
    (should (memq 'djot-modern-heading-1 (djot-modern-test--at "Title")))
    ;; Redo the deletion, then undo it after disabling the presentation mode.
    (undo-boundary)
    (undo-redo 1)
    (should (equal (buffer-substring-no-properties (point-min) 6) "Title"))
    (undo-boundary)
    (djot-modern-mode -1)
    (let ((last-command nil)) (undo-only 1))
    (djot-modern-test--undecorated (buffer-string))
    (should (equal (buffer-substring-no-properties (point-min) (point-max))
                   "# Title\n\n- item\n"))))

(ert-deftest djot-modern-test-copy-kill-and-yank ()
  (dolist (kill '(nil t))
    (djot-modern-test--buffer "# Title\n\n- item\n"
      (let ((kill-ring nil) (kill-ring-yank-pointer nil)
            (yank-excluded-properties nil) (foreign "foreign"))
        (djot-modern-mode 1)
        (djot-modern-test--fontify)
        (with-silent-modifications
          (font-lock-prepend-text-property 1 3 'face 'warning)
          (put-text-property 1 3 'help-echo "keep")
          (put-text-property 10 12 'display foreign))
        (let ((buffer-read-only (not kill)))
          (if kill (kill-region (point-min) (point-max))
            (kill-ring-save (point-min) (point-max))))
        (djot-modern-test--undecorated (car kill-ring))
        (unless kill
          (should (djot-modern-test--at "# " 'display))
          (should-not (buffer-modified-p)))
        (with-temp-buffer
          (yank)
          (should-not djot-modern-mode)
          (should (equal (buffer-substring-no-properties (point-min) (point-max))
                         "# Title\n\n- item\n"))
          (djot-modern-test--undecorated (buffer-string))
          (should-not (get-text-property 1 'display))
          (should (eq foreign (get-text-property 10 'display)))
          (should (memq 'warning (get-text-property 1 'face)))
          (should (equal "keep" (get-text-property 1 'help-echo))))))))

(ert-deftest djot-modern-test-transfer-filter-coexistence-and-cleanup ()
  (djot-modern-test--buffer "# Title\n"
    (let* ((original filter-buffer-substring-function)
           (calls 0)
           (filter (lambda (beg end delete)
                     (cl-incf calls)
                     (let ((text (funcall original beg end delete)))
                       (put-text-property 0 (length text) 'help-echo "filtered" text)
                       text))))
      (setq-local filter-buffer-substring-function filter)
      (dotimes (_ 3)
        (djot-modern-mode 1)
        (djot-modern-test--fontify)
        (let ((text (filter-buffer-substring (point-min) (point-max))))
          (djot-modern-test--undecorated text)
          (should (equal "filtered" (get-text-property 0 'help-echo text))))
        (djot-modern-mode -1)
        (should (eq filter filter-buffer-substring-function))
        (should-not (memq #'djot-modern--clear before-change-functions)))
      (should (= calls 3))
      (cl-letf (((symbol-function 'treesit-parser-add-notifier)
                 (lambda (&rest _) (error "Injected registration failure"))))
        (should-error (djot-modern-mode 1)))
      (should (eq filter filter-buffer-substring-function))
      (should-not (memq #'djot-modern--clear before-change-functions)))))

(ert-deftest djot-modern-test-existing-parser-and-properties ()
  (djot-modern-test--buffer "# Title\n\n- item\n"
    (let ((parser (treesit-parser-create 'djot))
          (foreign (propertize "custom" 'face 'warning)))
      (font-lock-add-keywords nil '(("Title" . font-lock-warning-face)))
      (font-lock-mode 1)
      (put-text-property 1 3 'display foreign)
      (put-text-property 1 3 'help-echo "keep")
      (djot-modern-mode 1)
      (djot-modern-test--fontify)
      (should (eq foreign (get-text-property 1 'display)))
      (should (memq 'font-lock-warning-face (djot-modern-test--at "Title")))
      (djot-modern-mode -1)
      (djot-modern-test--fontify)
      (should font-lock-mode)
      (should (equal (treesit-parser-list) (list parser)))
      (should (eq foreign (get-text-property 1 'display)))
      (should (equal "keep" (get-text-property 1 'help-echo)))
      (should (eq 'font-lock-warning-face (djot-modern-test--at "Title")))
      (should-not (memq #'djot-modern--changed (treesit-parser-notifiers parser))))))

(ert-deftest djot-modern-test-narrowing-and-major-mode-change ()
  (djot-modern-test--buffer "# First\n\n# Second\n"
    (narrow-to-region 10 (point-max))
    (djot-modern-mode 1)
    (djot-modern-test--fontify)
    (widen)
    (djot-modern-test--fontify)
    (should (djot-modern-test--at "# First" 'display))
    (narrow-to-region 10 (point-max))
    (djot-modern-mode -1)
    (widen)
    (should-not (text-property-not-all (point-min) (point-max) 'display nil))
    (djot-modern-mode 1)
    (djot-modern-test--fontify)
    (fundamental-mode)
    (should-not (treesit-parser-list))
    (should-not (text-property-not-all (point-min) (point-max) 'display nil))))

(ert-deftest djot-modern-test-enable-failure ()
  (djot-modern-test--buffer "# Title\n"
    (cl-letf (((symbol-function 'treesit-ready-p) (lambda (&rest _) nil)))
      (should-error (djot-modern-mode 1) :type 'user-error))
    (should-not djot-modern-mode)
    (should-not djot-modern--active)
    (should-not font-lock-mode)
    (should-not (treesit-parser-list))
    (cl-letf (((symbol-function 'djot-modern--patterns)
               (lambda () '((nonexistent_grammar_node) @heading))))
      (should-error (djot-modern-mode 1) :type 'treesit-query-error))
    (should-not djot-modern-mode)
    (should-not (treesit-parser-list))))

(ert-deftest djot-modern-test-options ()
  (djot-modern-test--buffer "# Title\n\n- item\n\n*bold*\n"
    (let ((djot-modern-replace-markers nil) (djot-modern-inline nil))
      (djot-modern-mode 1)
      (djot-modern-test--fontify)
      (should (memq 'djot-modern-heading-1 (djot-modern-test--at "Title")))
      (should-not (djot-modern-test--at "bold"))
      (should-not (text-property-not-all (point-min) (point-max) 'display nil)))))

(ert-deftest djot-modern-test-ordinary-and-structural-edits ()
  (djot-modern-test--buffer "# Title\n\n*bold*\n\n# Later\n"
    (djot-modern-mode 1)
    (djot-modern-test--fontify)
    ;; A same-node change must acquire the heading face without a notifier range.
    (goto-char 5)
    (insert "fresh")
    (djot-modern-test--fontify)
    (should (memq 'djot-modern-heading-1 (djot-modern-test--at "fresh")))
    ;; An opening fence changes the interpretation of distant markers.
    (goto-char (point-min))
    (insert "```\n")
    (font-lock-ensure (point-min) 5)
    (djot-modern-test--fontify)
    (should-not (djot-modern-test--at "# Later" 'display))
    (should-not (memq 'djot-modern-strong (djot-modern-test--at "bold")))
    (goto-char (point-min))
    (delete-region (point) (+ (point) 4))
    (font-lock-ensure (point-min) 5)
    (djot-modern-test--fontify)
    (should (djot-modern-test--at "# Later" 'display))
    (should (memq 'djot-modern-strong (djot-modern-test--at "bold")))
    (goto-char (point-min))
    (delete-char 1)
    (djot-modern-test--fontify)
    (should-not (djot-modern-test--at "fresh" 'display))
    (should-not (memq 'djot-modern-heading-1 (djot-modern-test--at "fresh")))))

(ert-deftest djot-modern-test-incremental-query-bounds ()
  (djot-modern-test--buffer (apply #'concat (make-list 2000 "# Title\n\nbody *bold*\n\n"))
    (djot-modern-mode 1)
    (djot-modern-test--fontify)
    (let ((original (symbol-function 'treesit-query-capture)) spans)
      (cl-letf (((symbol-function 'treesit-query-capture)
                 (lambda (node query &optional beg end node-only)
                   (push (- end beg) spans)
                   (funcall original node query beg end node-only))))
        (goto-char (/ (point-max) 2))
        (insert "x")
        (font-lock-ensure (line-beginning-position) (line-end-position)))
      (should spans)
      (should (< (apply #'max spans) 1000)))))

(ert-deftest djot-modern-test-tree-sitter-font-lock-coexistence ()
  (djot-modern-test--buffer "# Title\n\n*bold*\n"
    ;; The same Emacs fontification seam used by the official djot-ts-mode.
    (let ((parser (treesit-parser-create 'djot)))
      (setq-local treesit-font-lock-settings
                  (treesit-font-lock-rules
                   :language 'djot :feature 'heading
                   '((heading) @font-lock-function-name-face)))
      (setq-local treesit-font-lock-feature-list '((heading)))
      (treesit-major-mode-setup)
      (font-lock-mode 1)
      (djot-modern-mode 1)
      (djot-modern-test--fontify)
      (should (memq 'djot-modern-heading-1 (djot-modern-test--at "Title")))
      (should (memq 'font-lock-function-name-face (djot-modern-test--at "Title")))
      (djot-modern-mode -1)
      (djot-modern-test--fontify)
      (should (eq 'font-lock-function-name-face (djot-modern-test--at "Title")))
      (should (equal (treesit-parser-list) (list parser))))))

(ert-deftest djot-modern-test-continuations-nesting-and-eob ()
  (djot-modern-test--buffer
      "# First\n# continuation\n\n> - outer\n>\n>   ```\n>   # literal\n>   ```\n\n- [ ] final"
    (djot-modern-mode 1)
    (djot-modern-test--fontify)
    (should (equal "◉ " (substring-no-properties
                         (djot-modern-test--at "# continuation" 'display))))
    (should-not (djot-modern-test--at "# literal" 'display))
    (should (djot-modern-test--at "[ ]" 'display))
    (goto-char (point-min))
    (search-forward "[ ]")
    (backward-char 2)
    (delete-char 1)
    (insert "x")
    (djot-modern-test--fontify)
    (should (equal "☑" (substring-no-properties
                        (djot-modern-test--at "[x]" 'display))))))

(ert-deftest djot-modern-test-late-enable-failure-and-modified-state ()
  (djot-modern-test--buffer "# Title\n"
    (set-buffer-modified-p t)
    (cl-letf (((symbol-function 'treesit-parser-add-notifier)
               (lambda (&rest _) (error "Injected registration failure"))))
      (should-error (djot-modern-mode 1)))
    (should-not djot-modern-mode)
    (should-not djot-modern--active)
    (should-not (treesit-parser-list))
    (should-not (advice-member-p #'djot-modern--clear
                                font-lock-unfontify-region-function))
    (should (buffer-modified-p))
    (djot-modern-mode 1)
    (djot-modern-test--fontify)
    (djot-modern-mode -1)
    (should (buffer-modified-p))))

(ert-deftest djot-modern-test-table-edits-and-foreign-display ()
  (djot-modern-test--buffer "| a | b |\n| - | - |\n| c | d |\n"
    (djot-modern-mode 1)
    (djot-modern-test--fontify)
    (goto-char (point-max))
    (insert "| `x|y` | e\\|f |\n")
    (djot-modern-test--fontify)
    (should-not (djot-modern-test--at "|y" 'display))
    (should-not (djot-modern-test--at "|f" 'display))
    ;; Do not erase a later owner's replacement during teardown.
    (let ((foreign "other"))
      (put-text-property 1 2 'display foreign)
      (djot-modern-mode -1)
      (should (eq foreign (get-text-property 1 'display))))))

(ert-deftest djot-modern-test-marker-layout-preserves-whitespace ()
  (djot-modern-test--buffer
      "- parent\n\n  - first\n  - second\n\n> quote\n>\n> after\n\n***\n\nafter rule\n"
    (djot-modern-mode 1)
    (djot-modern-test--fontify)
    (should (djot-modern-test--at "- second" 'display))
    (should-not (djot-modern-test--at "  - second" 'display))
    (goto-char (point-min))
    (while (search-forward "\n" nil t)
      (should-not (get-text-property (1- (point)) 'display)))))

(define-derived-mode djot-modern-test--base-mode text-mode "DjotTest"
  "Provide base fontification for mode-hook lifecycle tests."
  (setq-local font-lock-defaults '((("Title" . font-lock-warning-face)))))

(ert-deftest djot-modern-test-major-mode-hook-font-lock ()
  (dolist (settings '((t t t)
                      (t (djot-modern-test--base-mode) t)
                      (t (not text-mode) t)
                      (t (not djot-modern-test--base-mode) nil)
                      (nil t nil)))
    (djot-modern-test--buffer "# Title\n"
      (let ((global-font-lock-mode (nth 0 settings))
            (font-lock-global-modes (nth 1 settings))
            (djot-modern-test--base-mode-hook '(djot-modern-mode)))
        (djot-modern-test--base-mode)
        (should djot-modern-mode)
        (djot-modern-test--fontify)
        (djot-modern-mode -1)
        (should (eq (not (null font-lock-mode)) (nth 2 settings)))
        (when font-lock-mode
          (djot-modern-test--fontify)
          (should (eq (djot-modern-test--at "Title") 'font-lock-warning-face)))
        (should-not (memq #'djot-modern--after-major-mode
                          after-change-major-mode-hook))))))

(ert-deftest djot-modern-test-manually-disabled-base-font-lock ()
  (djot-modern-test--buffer "# Title\n"
    (let ((global-font-lock-mode t) (font-lock-global-modes t))
      (djot-modern-test--base-mode)
      (font-lock-mode -1)
      (djot-modern-mode 1)
      (djot-modern-test--fontify)
      (djot-modern-mode -1)
      (should-not font-lock-mode)
      (should-not (memq #'djot-modern--after-major-mode
                        after-change-major-mode-hook)))))

;;; djot-modern-test.el ends here
