;;; gui-test.el --- Redisplay-level presentation regressions -*- lexical-binding: t; -*-
(require 'djot-modern-test)

(defmacro djot-modern-gui-test--buffer (text &rest body)
  "Display TEXT in a real window and evaluate BODY."
  (declare (indent 1))
  `(save-window-excursion
     (djot-modern-test--buffer ,text
       (delete-other-windows)
       (switch-to-buffer (current-buffer))
       (djot-modern-mode 1)
       (goto-char (point-min))
       (redisplay t) (sit-for 0.1)
       ,@body)))

(defun djot-modern-gui-test--xy (position)
  "Return the actual displayed pixel coordinates of POSITION."
  (posn-x-y (or (posn-at-point position) (error "Position %d not displayed" position))))

(defun djot-modern-gui-test--pipes ()
  "Return each real table row's displayed pipe x coordinates."
  (let (rows)
    (djot-map-nodes
     (lambda (row)
       (when (member (treesit-node-type row) '("table_header" "table_row"))
         (push (cl-loop for i below (treesit-node-child-count row)
                        for child = (treesit-node-child row i)
                        when (equal (treesit-node-type child) "|")
                        collect (car (djot-modern-gui-test--xy (treesit-node-end child)))) rows))))
    (nreverse rows)))

(ert-deftest djot-modern-gui-actual-fonts-and-scripts ()
  (should (display-graphic-p))
  (djot-modern-gui-test--buffer "Prose with H~2~O and x^2^.\n\n> Quoted prose.\n\n```elisp\n(defun hello () \"hello\")\n```\n\n| Key | Value |\n|-----|-------|\n| one | two |\n"
    (let ((prose (font-get (font-at (djot-modern-test--position "Prose")) :family))
          (quote (font-get (font-at (djot-modern-test--position "Quoted")) :family))
          (code (font-get (font-at (djot-modern-test--position "defun")) :family))
          (table (font-get (font-at (djot-modern-test--position "Key")) :family)))
      (should (equal prose quote))
      (should (equal code table))
      (should-not (equal prose code)))
    (let ((body (cdr (djot-modern-gui-test--xy (djot-modern-test--position "H~"))))
          (sub (cdr (djot-modern-gui-test--xy (djot-modern-test--position "2~"))))
          (sup (cdr (djot-modern-gui-test--xy (djot-modern-test--position "2^")))))
      (should (> sub body))
      (should (< sup sub)))))

(ert-deftest djot-modern-gui-initial-code-background ()
  (should (display-graphic-p))
  (dolist (displayed-first '(t nil))
    (ert-info ((format "Activate %s first display" (if displayed-first "after" "before")))
      (save-window-excursion
        (djot-modern-test--buffer "Ordinary prose.\n\n```elisp\n(defun hello () (+ 1 2))\n```\n"
          (let ((source (buffer-string))
                (position (point))
                (tick (buffer-chars-modified-tick))
                (code (djot-modern-test--position "defun"))
                (height (face-attribute 'fixed-pitch :height))
                (themes custom-enabled-themes)
                (foreign (make-overlay 1 2)))
            (overlay-put foreign 'help-echo "foreign")
            (buffer-enable-undo) (setq buffer-undo-list nil)
            (cl-labels
                ((settle () (redisplay t) (sit-for 0.1) (redisplay t))
                 (shaded ()
                   (settle)
                   (should (stringp djot-modern--block-background))
                   (should-not (equal djot-modern--block-background
                                      (face-background 'default nil t)))
                   (should (cl-some
                            (lambda (overlay)
                              (equal (overlay-get overlay 'face)
                                     `(:background ,djot-modern--block-background :extend t)))
                            (djot-modern-test--owned code)))
                   (should (memq 'font-lock-keyword-face (get-text-property code 'face)))))
              (unwind-protect
                  (progn
                    (when displayed-first (switch-to-buffer (current-buffer)) (settle))
                    (should (eq (not (null (get-buffer-window))) displayed-first))
                    (should-not djot-modern--block-background)
                    (djot-modern-mode 1)
                    (unless displayed-first (switch-to-buffer (current-buffer)))
                    (shaded)
                    (let ((metrics djot-modern--metrics))
                      (shaded)
                      (should (eq metrics djot-modern--metrics)))
                    (when (fboundp 'djot-modern-gui--capture)
                      (djot-modern-gui--capture
                       (format "initial-code-background-%s.png" (if displayed-first "displayed" "undisplayed"))))
                    (djot-modern-mode -1) (settle)
                    (should-not (djot-modern-test--owned code))
                    (djot-modern-mode 1) (shaded)
                    (set-face-attribute 'fixed-pitch nil :height 180) (shaded)
                    (let (background)
                      (dolist (theme '(modus-operandi-tinted modus-vivendi-tinted))
                        (mapc #'disable-theme custom-enabled-themes)
                        (load-theme theme t)
                        (shaded)
                        (when background
                          (should-not (equal background djot-modern--block-background)))
                        (setq background djot-modern--block-background)))
                    (should (= position (point)))
                    (should (= tick (buffer-chars-modified-tick)))
                    (should (equal source (buffer-string)))
                    (should-not buffer-undo-list)
                    (should-not (buffer-modified-p))
                    (should (equal "foreign" (overlay-get foreign 'help-echo))))
                (mapc #'disable-theme custom-enabled-themes)
                (mapc (lambda (theme) (load-theme theme t)) (reverse themes))
                (set-face-attribute 'fixed-pitch nil :height height)))))))))

(ert-deftest djot-modern-gui-table-pixels-and-incremental-edit ()
  (djot-modern-gui-test--buffer
      "| Key | Value |\n|-----|-------|\n| short | longer words |\n| `x|y` | a\\|b |\n\n[site](https://djot.net)\n"
    (let* ((pipes (djot-modern-gui-test--pipes))
           (link (cl-find-if (lambda (ov) (overlay-get ov 'djot-link))
                             (overlays-at (djot-modern-test--position "site")))))
      (should (cl-every (lambda (row) (equal row (car pipes))) pipes))
      (goto-char (djot-modern-test--position "short"))
      (insert "very much wider ")
      ;; Actual JIT/redisplay, not a whole-buffer font-lock-ensure shortcut.
      (redisplay t) (sit-for 0.2)
      (let ((new (djot-modern-gui-test--pipes)))
        (should (cl-every (lambda (row) (equal row (car new))) new))
        (should (> (nth 1 (car new)) (nth 1 (car pipes)))))
      (should (overlay-buffer link))
      (djot-modern-mode -1)
      (redisplay t)
      (should-not (djot-modern-test--owned)))))

(ert-deftest djot-modern-gui-last-row-deletion ()
  (djot-modern-gui-test--buffer
      "| Key | Value |\n|-----|-------|\n| one | two |\n| very long last cell | wider |\n\nFollowing prose.\n"
    (let ((width (nth 1 (car (djot-modern-gui-test--pipes)))))
      (goto-char (djot-modern-test--position "| very"))
      (delete-region (line-beginning-position) (line-beginning-position 2))
      (redisplay t) (sit-for 0.2)
      (should (< (nth 1 (car (djot-modern-gui-test--pipes))) width)))))

(ert-deftest djot-modern-gui-table-alignment-directives ()
  (djot-modern-gui-test--buffer
      "| Left | Right | Center |\n|:-----|------:|:------:|\n| long word | wider text | wide middle |\n| l | r | c |\n"
    (let ((right-short (car (djot-modern-gui-test--xy (djot-modern-test--position "r |"))))
          (right-long (car (djot-modern-gui-test--xy (djot-modern-test--position "wider text"))))
          (center-short (car (djot-modern-gui-test--xy (djot-modern-test--position "c |"))))
          (center-long (car (djot-modern-gui-test--xy (djot-modern-test--position "wide middle")))))
      (should (> right-short right-long))
      (should (> center-short center-long)))
    (let ((pipes (djot-modern-gui-test--pipes)))
      (should (cl-every (lambda (row) (equal row (car pipes))) pipes)))))

(ert-deftest djot-modern-gui-theme-and-font-refresh ()
  (djot-modern-gui-test--buffer "# Theme heading\n\n| Key | Value |\n|-----|-------|\n| one | longer words |\n"
    (let ((source (buffer-substring-no-properties (point-min) (point-max)))
          (original (face-attribute 'fixed-pitch :height))
          (width (car (last (car (djot-modern-gui-test--pipes))))))
      (unwind-protect
          (progn
            (set-face-attribute 'fixed-pitch nil :height 180)
            (redisplay t) (sit-for 0.2) (redisplay t)
            (should (> (car (last (car (djot-modern-gui-test--pipes)))) width))
            (dolist (theme '(modus-operandi-tinted modus-vivendi-tinted))
              (mapc #'disable-theme custom-enabled-themes)
              (load-theme theme t)
              (redisplay t) (sit-for 0.1) (redisplay t)
              (should (equal (face-foreground 'djot-modern-heading-1 nil t)
                             (face-foreground 'outline-1 nil t)))
              (should (equal source (buffer-substring-no-properties (point-min) (point-max))))))
        (set-face-attribute 'fixed-pitch nil :height original)))))

(ert-deftest djot-modern-gui-empty-cells ()
  (djot-modern-gui-test--buffer
      "# Empty cells\n\n|a||c|\n|:-|--:|:-:|\n||b|c|\n|a|b||\n||||\n|1|2|3|\n"
    (let ((pipes (djot-modern-gui-test--pipes)))
      (should (cl-every (lambda (row) (= (length row) 4)) pipes))
      (should (cl-every (lambda (row) (equal row (car pipes))) pipes)))
    (when (fboundp 'djot-modern-gui--capture)
      (djot-modern-gui--capture "empty-cells.png"))))

(ert-deftest djot-modern-gui-real-preview-table-composition ()
  (require 'djot-preview)
  (let ((directory (make-temp-file "djot-modern-preview-test-" t)))
    (unwind-protect
        (let ((default-directory (file-name-as-directory directory)))
          (with-temp-file "wide.svg"
            (insert "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"360\" height=\"64\"><rect width=\"360\" height=\"64\" rx=\"8\" fill=\"#397e92\"/><circle cx=\"35\" cy=\"32\" r=\"18\" fill=\"#ebcf80\"/></svg>"))
          (djot-modern-gui-test--buffer
              "# Explicit local previews\n\n| Content | Status |\n|---|---|\n| ![local](wide.svg) | image |\n| $`\\rule{180pt}{0.4pt}+x^2` | math |\n| `code _literal_` | code |\n\n[Link](https://djot.net)\n"
            (let ((foreign (make-overlay (- (point-max) 5) (point-max)))
                  (position (point))
                  (source (buffer-substring-no-properties (point-min) (point-max)))
                  (tick (buffer-chars-modified-tick)))
              (overlay-put foreign 'face 'bold)
              (buffer-enable-undo) (setq buffer-undo-list nil)
              (cl-labels
                  ((settle () (redisplay t) (sit-for 0.1) (redisplay t))
                   (aligned ()
                     (settle)
                     (let ((pipes (djot-modern-gui-test--pipes)))
                       (should (cl-every (lambda (row) (equal row (car pipes))) pipes)))))
                (djot-display-inline-images)
                (djot-preview-math t)
                ;; This must relayout from overlay changes alone, not a text tick
                ;; or a whole-buffer refresh inserted only by the test.
                (aligned)
                (should (= tick (buffer-chars-modified-tick)))
                (should (= position (point)))
                (should-not buffer-undo-list)
                (should-not (buffer-modified-p))
                (should (equal source (buffer-substring-no-properties (point-min) (point-max))))
                (dotimes (_ 3) (djot-refresh) (aligned))
                (let ((width (nth 1 (car (djot-modern-gui-test--pipes)))))
                  (djot-clear-math-preview)
                  (djot-remove-inline-images)
                  (aligned)
                  (should-not (= width (nth 1 (car (djot-modern-gui-test--pipes))))))
                (djot-preview-math t) (aligned)
                (djot-display-inline-images) (aligned)
                (djot-show-source 1) (settle)
                (should (cl-every (lambda (o) (null (overlay-get o 'display))) djot--preview-overlays))
                (should (equal source (buffer-substring-no-properties (point-min) (point-max))))
                (djot-show-source 0) (aligned)
                (djot-modern-mode -1) (settle)
                (should (= 2 (length djot--preview-overlays)))
                (should (cl-every (lambda (o) (overlay-get o 'display)) djot--preview-overlays))
                (djot-modern-mode 1)
                (djot-preview-math t) (aligned)
                (dolist (theme '(modus-operandi-tinted modus-vivendi-tinted))
                  (mapc #'disable-theme custom-enabled-themes) (load-theme theme t)
                  (settle)
                  (should-not (cl-find 'math djot--preview-overlays :key (lambda (o) (overlay-get o 'djot-preview))))
                  (djot-preview-math t) (aligned)
                  (when (fboundp 'djot-modern-gui--capture)
                    (djot-modern-gui--capture (format "previews-%s.png" theme))))
                (let ((height (face-attribute 'default :height)))
                  (unwind-protect
                      (progn
                        (set-face-attribute 'default nil :height (+ height 20))
                        (settle)
                        (should-not (cl-find 'math djot--preview-overlays :key (lambda (o) (overlay-get o 'djot-preview))))
                        (djot-preview-math t) (aligned))
                    (set-face-attribute 'default nil :height height)))
                ;; Source alignment measures source, not rendered-image pixels.
                (goto-char (djot-modern-test--position "| Content"))
                (djot-table-align)
                (let ((aligned-source (buffer-substring-no-properties (point-min) (point-max))))
                  (dotimes (_ 2)
                    (djot-display-inline-images) (djot-preview-math t) (aligned)
                    (djot-table-align)
                    (should (equal aligned-source (buffer-substring-no-properties (point-min) (point-max)))))
                  (djot-display-inline-images) (djot-preview-math t) (aligned))
                (should (overlay-buffer foreign))
                (should (eq 'bold (overlay-get foreign 'face)))))))
      (delete-directory directory t))))


(ert-deftest djot-modern-gui-two-frame-table-geometry ()
  (require 'djot-preview)
  (let* ((first (selected-frame))
         (second (make-frame '((name . "Djot large") (left . 1120) (top . 0))))
         (buffer (generate-new-buffer "two-frame Djot"))
         (directory (make-temp-file "djot-two-frame-" t))
         (old-height (face-attribute 'fixed-pitch :height first)))
    (unwind-protect
        (progn
          (with-temp-file (expand-file-name "wide.svg" directory)
            (insert "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"280\" height=\"32\"><rect width=\"280\" height=\"32\" fill=\"#397e92\"/></svg>"))
          ;; Activation while undisplayed must not retain another buffer's frame.
          (with-current-buffer buffer
            (setq default-directory (file-name-as-directory directory))
            (insert "| A | B | C |\n|:--|:--|:--|\n| short | one | x |\n| a much longer entry | yy | z |\n| ![local](wide.svg) | image | x |\n| $`x^2` | math | z |\n\n> ````python\n> @cache\n> def f():\n>     return 1 > 0\n> `````")
            (djot-mode) (djot-modern-mode 1)
            (set-buffer-modified-p nil)
            (buffer-enable-undo) (setq buffer-undo-list nil))
          (dolist (entry (list (cons first 110) (cons second 220)))
            (set-face-attribute 'fixed-pitch (car entry) :family "Fira Code" :height (cdr entry))
            (set-frame-size (car entry) 1080 640 t)
            (set-window-buffer (frame-selected-window (car entry)) buffer)
            (set-window-point (frame-selected-window (car entry)) 1)
            (set-window-start (frame-selected-window (car entry)) 1))
          (with-current-buffer buffer
            (let ((source (buffer-substring-no-properties (point-min) (point-max)))
                  (tick (buffer-chars-modified-tick))
                  (foreign (make-overlay 1 2)))
              (overlay-put foreign 'help-echo "foreign")
              (cl-labels
                  ((aligned (label)
                     (redisplay t) (sit-for 0.15) (redisplay t)
                     (dolist (frame (list first second))
                       (with-selected-window (frame-selected-window frame)
                         (let ((pipes (djot-modern-gui-test--pipes)))
                           (message "Two-frame %s height=%S pipes=%S" label
                                    (face-attribute 'fixed-pitch :height frame) pipes)
                           (should (cl-every (lambda (row) (equal row (car pipes))) pipes)))
                       (when (getenv "DJOT_GUI_DIR")
                         (let ((coding-system-for-write 'no-conversion))
                           (write-region
                            (x-export-frames (list frame) 'png) nil
                            (expand-file-name (format "two-frame-%s-%s.png" label (if (eq frame first) "small" "large"))
                                              (getenv "DJOT_GUI_DIR")) nil 'silent)))))))
                (select-frame-set-input-focus first) (aligned "small-selected")
                (save-excursion
                  (goto-char (point-min)) (search-forward "@cache")
                  (should (memq 'font-lock-type-face (get-text-property (- (point) 6) 'face)))
                  (goto-char (point-max)) (backward-char)
                  (should (equal "▰" (get-char-property (point) 'display (frame-selected-window first)))))
                (select-frame-set-input-focus second) (aligned "large-selected")
                (set-face-attribute 'fixed-pitch first :height 150) (aligned "font-changed")
                (djot-display-inline-images) (djot-preview-math t) (aligned "previews")
                (djot-show-source 1) (redisplay t)
                (djot-show-source 0) (aligned "source-restored")
                (djot-modern-mode -1) (redisplay t)
                (should-not (djot-modern-test--owned))
                (should (= 2 (length djot--preview-overlays)))
                (djot-modern-mode 1) (aligned "reenabled")
                (mapc #'disable-theme custom-enabled-themes)
                (load-theme 'modus-operandi-tinted t)
                ;; Loading a theme resets frame-local faces; restore distinct
                ;; metrics so the edit/undo phases still exercise both layouts.
                (set-face-attribute 'fixed-pitch first :height 150)
                (set-face-attribute 'fixed-pitch second :height 220)
                (aligned "theme-changed")
                (djot-preview-math t) (aligned "theme-previews")
                (should (overlay-buffer foreign))
                (should (= tick (buffer-chars-modified-tick)))
                (should-not buffer-undo-list)
                (should (equal source (buffer-substring-no-properties (point-min) (point-max))))
                (goto-char (point-min)) (search-forward "short")
                (insert " plus an edited cell") (undo-boundary)
                (aligned "edited")
                (let ((inhibit-message t)) (undo 1))
                (aligned "undone")
                (should (equal source (buffer-substring-no-properties (point-min) (point-max))))
                (delete-overlay foreign)))))
      (when (buffer-live-p buffer) (kill-buffer buffer))
      (delete-frame second)
      (select-frame-set-input-focus first)
      (set-face-attribute 'fixed-pitch first :height old-height)
      (delete-directory directory t))))

(provide 'gui-test)
;;; gui-test.el ends here
