;;; table-integration-test.el --- Composed editing and presentation -*- lexical-binding: t; -*-
(require 'djot-modern-test)

(ert-deftest djot-modern-table-align-does-not-count-modern-padding ()
  (should (fboundp 'djot-table-align))
  (djot-modern-test--buffer
      "| Name | Value |\n|------|------:|\n| [a](https://example.org/a/long/destination) | one |\n| `x|y` | two |\n"
    (goto-char (point-min))
    (djot-table-align)
    ;; Hidden URL source must not dictate the width of visible header cells.
    (save-excursion
      (goto-char (point-min))
      (should (< (- (line-end-position) (line-beginning-position)) 35)))
    (let ((aligned (buffer-substring-no-properties (point-min) (point-max))))
      (djot-modern-mode 1)
      (dotimes (_ 3)
        (djot-table-align)
        (djot-refresh)
        (should (equal aligned (buffer-substring-no-properties (point-min) (point-max)))))
      (djot-modern-mode -1)
      (djot-table-align)
      (should (equal aligned (buffer-substring-no-properties (point-min) (point-max))))
      (djot-show-source 1)
      (should (equal aligned (buffer-substring-no-properties (point-min) (point-max))))
      (djot-table-align)
      (let ((source-aligned (buffer-substring-no-properties (point-min) (point-max))))
        (djot-modern-mode 1)
        (djot-table-align)
        (should (equal source-aligned (buffer-substring-no-properties (point-min) (point-max))))))))

(ert-deftest djot-modern-table-empty-cell-semantic-regression ()
  ;; This is a hard dependency regression, not a source reparsing fallback.
  ;; The original grammar consumed || as part of the next table_cell.
  (dolist (row '("|a||c|" "||b|c|" "|a|b||" "||||"))
    (djot-modern-test--buffer (concat row "\n|:-|--:|:-:|\n|1|2|3|\n")
      (djot-modern-mode 1)
      (let ((header (djot-node-at 1 "table_header")))
        (should header)
        (should (= 4 (length (djot-modern--table-pipes header))))
        (should (= 3 (length (djot-modern--table-cells header)))))
      (goto-char 1)
      (djot-table-align)
      (let ((aligned (buffer-substring-no-properties (point-min) (point-max))))
        (djot-table-align)
        (should (equal aligned (buffer-substring-no-properties (point-min) (point-max))))))))

(ert-deftest djot-modern-cell-measurement-respects-foreign-priority ()
  (djot-modern-test--buffer "| abcdef | x |\n"
    (let ((low (make-overlay 2 10)) (high (make-overlay 4 8))
          (own (make-overlay 3 9)))
      (overlay-put low 'display "low")
      (overlay-put low 'priority 10)
      (overlay-put high 'display "highest")
      (overlay-put high 'priority 20)
      (overlay-put high 'invisible 'foreign-hidden)
      (add-to-invisibility-spec 'foreign-hidden)
      (overlay-put own 'djot-modern t)
      (overlay-put own 'display "excluded padding")
      (overlay-put own 'priority 100)
      (let ((text (djot-modern--cell-text 3 9)))
        (should (= 6 (length text)))
        (should (equal "low" (get-text-property 0 'display text)))
        (should (equal "highest" (get-text-property 1 'display text)))
        (should (get-text-property 1 'invisible text))
        (should (equal "low" (get-text-property 5 'display text))))
      (should (equal "highest" (overlay-get high 'display)))
      (should (equal '(4 . 8) (cons (overlay-start high) (overlay-end high))))
      (should (equal "low" (overlay-get low 'display))))))

(provide 'table-integration-test)
;;; table-integration-test.el ends here
